### ISSUE TITLE
Missing License information

### ISSUE THREAD

**Issue by fedepell** [tnodir/luasys#13]
Would it be possible to add to the project the licensing information (ie. usual LICENSE / COPYRIGHT file) so as to make it easier / cleaner ( / more legal :-) ) to integrate into other projects? (ie. I', trying to integrate your module into a Yocto based system)

Many thanks!
F.

**Comment by tnodir** [comment]
Thanks, added MIT license.

**Comment by fedepell** [comment]
Many thanks for the immediate action!
