### ISSUE TITLE
Documentation is unreachable

### ISSUE THREAD

**Issue by adrfantini** [tnodir/luasys#17]
http://luaforge.net/projects/luasys does not load, for some reason.

Is there any other place users can get the docs? Thank you!

**Comment by tnodir** [comment]
There was not any docs in the Luaforge.
All stuff is here in Github.
Please read the sources.

**Comment by adrfantini** [comment]
Oh, so there is no documentation, ok, thanks.

I guess anyway the about section could be updated if luaforge is down:
![Screenshot_20220321_111112](https://user-images.githubusercontent.com/12826141/159241080-ac3fc8a0-1e47-42d2-b5fd-e46c6f053cc8.png)

Thanks anyway.
