### ISSUE TITLE
Application stop working if encounter thread error

### ISSUE THREAD

**Issue by hyee** [tnodir/luasys#9]
Hi,

As shown in screen-shot below of testing the script stdin.lua, if the thread encounters an error, the program will stop working and pop-up a Windows  dialog. This may not be a good ways, at least the dialog is not expected.
![sshot-1](https://cloud.githubusercontent.com/assets/761520/6651354/8f5c2934-ca79-11e4-81e2-25331ea8ba03.png)

For file "stdin.lua", I simply change sys.stdout:write("Worker:\tInput: ", line) as "os.execute(line)", because I may need luasys to do the similar functions in my progam.

My platform is Win7 64bit. Thank you.

**Comment by tnodir** [comment]
Hi,

> ... if the thread encounters an error, the program will stop working and pop-up a Windows dialog.

Uncaught errors in the threads will stop whole program. Use pcall().

> ... I simply change sys.stdout:write("Worker:\tInput: ", line) as "os.execute(line)"

Just remove assertion in the 59 line too.
